ISOv4Plugin/ExtensionMethods/XmlExtensions.cs
ISOv4Plugin/ISOModels/ISOAllocationStamp.cs
ISOv4Plugin/Mappers/AllocationStampMapper.cs
ISOv4Plugin/Mappers/CommentAllocationMapper.cs

Allocation Stamps:
-Handling recordings with only the Start attribute defined
-Duration attribute has a max value of uint
Signed-off-by: Jason Roesbeke <jason.roesbeke@cnhind.com>

Allocation Stamps:

---

ISOv4Plugin/ISOModels/ISOAllocationStamp.cs

Not "short-circuiting" on a XML reader such as returning null if ASP.Start is empty; such conditionals should be in the Mappers.  ISO specs live in the Mappers and the ISOModels only need to do the serializing and deserializing of the data. 
This could also allow to keep all IError implementations (reporting errors during mapping) regarding ISO specs inside the Mappers.
Made this change based on what was discussed at the ADAPT Technical Committee Meeting 13/12/2017.
Signed-off-by: Jason Roesbeke jason.roesbeke@cnhind.com

Not "short-circuiting" on a XML reader, ISO spec conditionals should be in the Mappers.

---

ISOv4Plugin/ISOModels/ISO11783_TaskData.cs
ISOv4Plugin/Mappers/GuidancePatternMapper.cs
ISOv4Plugin/Mappers/LoggedDataMappers/Import/ActualLoadingSystemStatusMeterCreator.cs
ISOv4Plugin/Mappers/LoggedDataMappers/Import/CondensedWorkStateMeterCreator.cs
ISOv4Plugin/Mappers/LoggedDataMappers/Import/ConnectorTypeMeterCreator.cs
ISOv4Plugin/Mappers/LoggedDataMappers/Import/IEnumeratedMeterCreator.cs
ISOv4Plugin/Mappers/LoggedDataMappers/Import/NetWeightStateMeterCreator.cs
ISOv4Plugin/Mappers/LoggedDataMappers/Import/PrescriptionControlMeterCreator.cs
ISOv4Plugin/Mappers/LoggedDataMappers/Import/SectionControlStateMeterCreator.cs
ISOv4Plugin/Mappers/LoggedDataMappers/Import/SectionMapper.cs
ISOv4Plugin/Mappers/LoggedDataMappers/Import/SkyConditionsMeterCreator.cs
ISOv4Plugin/Mappers/LoggedDataMappers/Import/SpatialRecordMapper.cs
ISOv4Plugin/Mappers/LoggedDataMappers/Import/WorkStateMeterCreator.cs
ISOv4Plugin/Mappers/LoggedDataMappers/Import/WorkingDataMapper.cs

Guidance Pattern import was omitting the shape.   Adding for all patterns including a partial implementation for Pivots which are currently under discussion.
Proprietary DDIs were being suppressed.   Reporting out with a default unit of measure.

Setting Shapes on Guidance Patterns & Including Proprietary DDIs

---

ISOv4Plugin/ISOModels/ISO11783_TaskData.cs
ISOv4Plugin/Mappers/TaskDataMapper.cs
ISOv4Plugin/Plugin.cs

Rather than just "ISO Task Data," the Catalog.description provides a spot to expose the file path to the data.   This is useful when the plugin reads multiple TaskData.xml files and generates more than one adm model.

Setting file path into Catalog description

---

ISOv4Plugin/Mappers/LoggedDataMappers/Import/SectionMapper.cs
ISOv4Plugin/Mappers/LoggedDataMappers/Import/SpatialRecordMapper.cs
ISOv4Plugin/Mappers/LoggedDataMappers/Import/WorkingDataMapper.cs
ISOv4Plugin/Mappers/TimeLogMapper.cs
ISOv4Plugin/ObjectModel/DeviceElementHierarchy.cs
ISOv4Plugin/Representation/RepresentationMapper.cs

Added reporting of Product Allocations via vrProductIndex when there are multiple products on a task.
Moved bin elements to a unique depth in the device hierarchy.
Fixed issues where a DLV value was reported in the TLG.xml in addition to TLG.bin

Additional Air Seeder/Multiple Product Fixes

---

ISOv4Plugin/Mappers/TimeLogMapper.cs

Although it makes totally sense to have this optimization, it is not specified in ISO 11783-10. Thus, generated files will be incompatible with any 3rd party ISOXML implementation. I recommend to remove this optimization

Remove optimization to save space in BIN files

---

ISOv4Plugin/ExtensionMethods/XmlExtensions.cs

When running the Plugin on a machine with local Globalization settings, parsing of some attributes (like lat / lon coordinates) is wrong, as decimal separator is not recognized correctly

Fix XML extensions to properly parse decimal separator

---

AgGatewayISOPlugin.nuspec
ISOv4Plugin/ISOv4Plugin.csproj
ISOv4Plugin/Mappers/TaskDataMapper.cs
ISOv4Plugin/Representation/RepresentationMapper.cs

Upgrade to Framework 2.0.2
Fixing Import Mappings for Multiple DDI Matches
Allowing import of Miscategorized Tasks

Fixing Multiple DDI Match Mapping and Allowing import of Miscategorized Tasks

---

ISOv4Plugin/Mappers/TaskMapper.cs
ISOv4Plugin/Plugin.cs

Fix to set MeteredValue.DeviceConfigurationID if the device hasn't been created yet.
This was manifested when importing an air seeder dataset with separate bins.

 Fix to set MeteredValue.DeviceConfigurationID

---

ISOv4Plugin/ISOModels/ISOGrid.cs

Bug fix for case sensitive file systems.  This is needed if running on linux and the .bin file extension is upper case.

Case sensitive filesystem bug fix.

---

ISOv4Plugin/Mappers/LoggedDataMappers/Import/EnumeratedMeterFactory.cs
ISOv4Plugin/Representation/DdiLoader.cs

Suppressing Setpoint Workstate data in preference to incorrectly mapping to an actual state.
Alternatives longer term would be to add a representation in ADAPT for this concept (which is rare), or pass the data through as an ISO representation (which I initially pursued, leading to a cascade of changes including in the DDILoader, and handling null units in the RepresentationMapper, before ultimately setting aside the effort due to the non-existence of a "None" unit of measure in ADAPT).

Issue 92 Workaround, UOM Parsing Fix

---

ISOv4Plugin/Mappers/LoggedDataMappers/Import/SkyConditionsMeterCreator.cs

With a GS3 2630 data set I did run into an invalid typecast exception exporting this data set to ISO.

Avoid an invalid typecast exception

---

ISOv4Plugin/Mappers/LoggedDataMappers/Import/ActualLoadingSystemStatusMeterCreator.cs
ISOv4Plugin/Mappers/LoggedDataMappers/Import/CondensedWorkStateMeterCreator.cs
ISOv4Plugin/Mappers/LoggedDataMappers/Import/ConnectorTypeMeterCreator.cs
ISOv4Plugin/Mappers/LoggedDataMappers/Import/IEnumeratedMeterCreator.cs
ISOv4Plugin/Mappers/LoggedDataMappers/Import/NetWeightStateMeterCreator.cs
ISOv4Plugin/Mappers/LoggedDataMappers/Import/PrescriptionControlMeterCreator.cs
ISOv4Plugin/Mappers/LoggedDataMappers/Import/SectionControlStateMeterCreator.cs
ISOv4Plugin/Mappers/LoggedDataMappers/Import/SkyConditionsMeterCreator.cs
ISOv4Plugin/Mappers/LoggedDataMappers/Import/WorkStateMeterCreator.cs
ISOv4Plugin/Mappers/LoggedDataMappers/Import/WorkingDataMapper.cs
ISOv4Plugin/Mappers/PolygonMapper.cs
ISOv4Plugin/ObjectModel/DeviceElementHierarchy.cs

Fixing 3 issues: 
-Null check on exterior rings
-Multiple Y-Offset vales in binary data for same device element, 
-CondensedWorkstate logic fails to account for governing device element where multiple.

CondensedWorkstate, Polygon Exterior Ring and Binary Y-Offset Data fixes

---

ISOv4Plugin/Mappers/TimeLogMapper.cs

We are using ISO plugin for processing data in our project. While running integration tests against several data sets using XUnit framework, System.IO.IOException with a message "The process cannot access the file x because it is being used by another process" is thrown.
To solve this, a change is proposed in this PR to open binary file with read sharing access allowing multiple readers to access same file at the same time.

Allow reading binary files by multiple readers at the same time

---

ISOv4Plugin/Mappers/GridMapper.cs

Bin file extensions unified to prevent bug on linux machines when reading file info with lower case extension nad file has upper case

Bin file extensions lowercased to unify approach across solution

---

ISOv4Plugin/Mappers/PolygonMapper.cs

Hello, dealing with ISOXML files we need, when present, to import the designators (attribute B) of the boundary polygons.
In order to do that, we are submitting a couple of PRs,
this one in ISOV4Plugin, adds the code to populate appropriately the additional ContextItems field in the Shape class.
this PR depends on https://github.com/ADAPT/ADAPT/pull/301 that adds the field in the Shape class.

Adding Pr_ISOXML_Attribute_Designator ContextItem to boundary polygons

---

ISOv4Plugin/ISOModels/ISOGrid.cs
ISOv4Plugin/ObjectModel/GridDescriptor.cs

In some situations the `GRD.bin` files could be missing. This PR changes the plugin behavior to ignore them (instead of throwing a file access exception) same way as done for missing `TLG.bin` files.

Protect against missing GRD.bin files

---

ISOv4Plugin/ObjectModel/DeviceElementHierarchy.cs

This will fix an exception we've been seeing on a dataset `Sequence contains more than one matching element`
Line 402 in ISOv4Plugin/ObjectModel/DeviceElementHierarchy.cs creates an array containing `any` row width SpatialValue.
Line 428 (Where the exception occurs) uses Single because there is an assumption that the array created on 402 will only have one element, because why would the data report more than one row width?
It turns out that some datasets report row width twice, which would cause an exception here.

Replacing Single with First on array that can have more than one element

---

ISOv4Plugin/Mappers/GuidancePatternMapper.cs

preventing ill formed coding data like this
```
<GPN A="GPN-182" B="Eagle Creek" C="3"/>
```
from crashing the import

TAPMR-4942 - don't throw exception on invalid guidance data

---

ISOv4Plugin/ExtensionMethods/ExtensionMethods.cs
ISOv4Plugin/ISOModels/ISOTime.cs
ISOv4Plugin/Mappers/Factories/TimeLogMapperFactory.cs
ISOv4Plugin/Mappers/LoggedDataMappers/Import/SectionMapper.cs
ISOv4Plugin/Mappers/LoggedDataMappers/Import/SpatialRecordMapper.cs
ISOv4Plugin/Mappers/Manufacturers/CNH.cs
ISOv4Plugin/Mappers/Manufacturers/ManufacturerFactory.cs
ISOv4Plugin/Mappers/MultiFileTimeLogMapper.cs
ISOv4Plugin/Mappers/ProductMapper.cs
ISOv4Plugin/Mappers/TaskDataMapper.cs
ISOv4Plugin/Mappers/TaskMapper.cs
ISOv4Plugin/Mappers/TimeLogMapper.cs
ISOv4Plugin/ObjectModel/ISOSpatialRow.cs

This PR adds support for:
- using manufacturer private attributes (xml attributes that start with `P`) to fill in missing product properties.
- processing TLGs with more than 255 DLVs that are split across multiple .bin files. The data from these files is exposed as single OperationData entity.
- handling product allocations at different levels. The change prefers direct product allocation at the lowest level.
- correctly handling product component import.

Private attributes and multi-file TLG

---

ISOv4Plugin/Mappers/Factories/TimeLogMapperFactory.cs

`MultiFileTimeLogMapper` class has private fields which means a new instance of this class is needed when reading TLG files. This PR fixes the incorrect usage of this class by `TimeLogMapperFactory`.

Fixed usage of MultiFileTimeLogMapper

---

ISOv4Plugin/Mappers/ProductMapper.cs
ISOv4Plugin/Mappers/TimeLogMapper.cs

This PR includes following changes:
- set product category to Variety if product type is Variety
- splits operations with multiple forms of products (liquid, granular, etc.) into separate operations

Split time logs with different types of products into separate operations

---

ISOv4Plugin/ISOv4Plugin.csproj
ISOv4Plugin/Mappers/TimeLogMapper.cs

Allow for identifying product allocations via a ProductIndex on higher-level Device Elements that don't otherwise log data

Parent product allocations

---

ISOv4Plugin/Mappers/TimeLogMapper.cs
ISOv4Plugin/ObjectModel/DeviceElementHierarchy.cs

ISO Plugin has a special logic to detect a boom with a single bin. In such situations bin's children/sensors are moved to a new parent - boom. But the same logic is not applied to product allocations that still referencing bin element. As a result, product allocations can not be processed and missing from OperationData.
This PR addresses this limitation and adds logic to correctly handle this situation and attach product allocations to boom.

Single boom/bin and product allocations

---

ISOv4Plugin/Mappers/TimeLogMapper.cs

This PR adds support for scenarios where device hierarchies with different depths have product allocations assigned.
For example, liquid product is applied through Function->Boom->Unit and dry product through Function->Boom->Section->Unit. Previous logic would determine the lowest level from hierarchy for dry product (which is 4) and then filter out liquid product hierarchy (which has lowest level of 3). The end result is missing separate operation for liquid product.
The new logic keeps hierarchy of the same type (Unit) when leaf device element has not children. This results in two operation being created: one for liquid and one for dry products.

Products at different hierarchy levels

---

ISOv4Plugin/Mappers/TimeLogMapper.cs

Handle an edge case where spatial records with bad GPS data are used to find the UTC offset for unspecified date/time values.
Encountered input data where the `vrProductIndex` meter values were incorrect. Traced the problem to SpatialRecordMapper.cs around line 159, then into the `GovernsTimestamp` method, then into the `ToUtc` method. The spatial record timestamp values'  `Kind` is `DateTimeKind.Unspecified`, so `ToUtc()` uses `TaskDataMapper.GPSToLocalDelta` to adjust the value. However, after adjustment the timestamp values were nonsensical; e.g. `{8/4/2159 9:00:53 PM}`.
`TaskDataMapper.GPSToLocalDelta` is set at TimeLogMapper.cs, line 331, by getting the first spatial record and comparing its `TimeStart` value to the `GpsUtcDateTime` value. For the data in question, the first 76 …

Look for valid GPS date/time when determining TaskDataMapper.GPSToLocalDelta

---

ISOv4Plugin/Mappers/LoggedDataMappers/Import/WorkingDataMapper.cs

Seeing frequent NullReferenceExceptions thrown from `WorkingDataMapper.UpdateCondensedWorkingData` from CNH application data, specifically with this stack trace:
```
{System.NullReferenceException: Object reference not set to an instance of an object.
at AgGateway.ADAPT.ISOv4Plugin.Mappers.WorkingDataMapper.UpdateCondensedWorkingDatas(List`1 condensedWorkingDatas, ISODataLogValue dlv, DeviceElementUse deviceElementUse, List`1 pendingDeviceElementUses, DeviceHierarchyElement isoDeviceElementHierarchy)
at AgGateway.ADAPT.ISOv4Plugin.Mappers.WorkingDataMapper.Map(ISODataLogValue dlv, IEnumerable`1 isoSpatialRows, DeviceElementUse deviceElementUse, Byte order, List`1 pendingDeviceElementUses, DeviceHierarchyElement isoDeviceElementHierarchy)
at …
```

Fix NullReferenceException in WorkingDataMapper.UpdateCondensedWorkingData

---

ISOv4Plugin/Mappers/DeviceMapper.cs
ISOv4Plugin/Mappers/TaskDataMapper.cs
ISOv4Plugin/ObjectModel/DeviceElementHierarchy.cs
ISOv4Plugin/ObjectModel/ISOOperationData.cs

This PR resolves two issues from the latest set of changes to better support CNH data sets:
- missed handling of new sensor
- crash inside Visualizer due to use of derived class for OperationData

Address missed changes and crash in Visualizer

---

ISOv4Plugin/Mappers/GuidancePatternMapper.cs
ISOv4Plugin/Mappers/TimeLogMapper.cs
ISOv4Plugin/ObjectModel/DeviceElementHierarchy.cs

Two separate fixes for edge cases found from recent CNH data.
- Catch OverflowException in BinaryReader.ReadImplementGeometryValues and add the error to plugin errors collection
- Include the errors collection as an argument in several methods to allow the errors to be added to the `IPlugin.Errors` collection and available to the caller
- Handle a null `TaskMapper.DeviceElementHierarchies` value in `TimeLogMapper.ImportTimeLog()`
- Remove duplicate `using` statement in GuidancePatternMapper that was causing a warning

Handle OverflowException and NullReferenceException

---

ISOv4Plugin/Mappers/GuidancePatternMapper.cs

ISO data submitted to us for import contained an ABLine-type guidance pattern without any points, i.e.
```
<GGP A="GGP-1" B="xxxx">
<GPN A="GPN-1" B="xxxx" C="1" E="1" F="1" />
</GGP>
```
Rather than throwing a `System.InvalidOperationException`, this change allows the import to continue, adding information about the exception to the `plugin.Errors` collection. It also catches `ArgumentOutOfRangeException`, which would happen indexing LineString points for Pivot-type guidance patterns in the same method.

Handle exceptions thrown from GuidancePatternMapper.ImportGuidancePattern()

---

ISOv4Plugin/Mappers/TimeLogMapper.cs

We have a file that came in as CropProtection with 5.6.0 and comes in as Unknown with 5.6.1.  This change keeps most (all?) of the value of #249 while giving us the CropProtection designator back.

Keep valuable operation information from device when possible

---

ISOv4Plugin/Mappers/TimeLogMapper.cs

We have harvest data from a CNH Pro1200 display that is coming in as SowingAndPlanting with 5.6.2.  Additionally, we observed that sometimes Unknown is being returned from TimeLogMapper.GetOperationTypeFromLoggingDevices when there was a more meaningful operation available in the list.  This PR addresses those two issues with the following changes:
1. Stop forcing CategoryEnum.Variety to OperationTypeEnum.SowingAndPlanting (could be Harvesting)
2. In GetOperationTypeFromLoggingDevices, prefer a non-Unknown operation type when there are multiple options

Two fixes for reading CNH Pro1200 Harvest data
